### ISSUE TITLE
Missing tsconfig.json

### ISSUE THREAD

**Issue by Askadar** [sdr34/react-custom-hooks#13]
Since project is using typescript, what's reasoning to exclude tsconfig.json from git? One of the issues is that test for useOnClickOutside doesn't pass because TS is not configured to handle JSX by default.
Sample error when running tests without `compilerOptions.jsx = "react-jsx"`
```
src/__tests__/useOnClickOutside.spec.tsx:9:9 - error TS17004: Cannot use JSX unless the '--jsx' flag is provided.
```

**Comment by CosmicCoder-sudo** [comment]
added to git
